name: Deploy Contracts
on:
  push:
    branches:
      - alvarof2/contracts
  workflow_dispatch:

jobs:
  deploy-contracts:
    runs-on: ubuntu-latest
    permissions: # Must change the job token permissions to use Akeyless JWT auth
      id-token: write
      contents: read
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      #- name: Setup foundry
      #  uses: foundry-rs/foundry-toolchain@v1

      - name: Akeyless get L1 URL
        uses: docker://us-west1-docker.pkg.dev/devopsre/akeyless-public/akeyless-action:latest
        with:
          api-url: https://api.gateway.akeyless.celo-networks-dev.org
          access-id: p-kf9vjzruht6l
          static-secrets: '{"/static-secrets/devops-circle/alvaro-test-opstack-sepolia/l1-rpc-url":"L1_RPC_URL"}'

      - name: Akeyless get GS ADMIN private key
        uses: docker://us-west1-docker.pkg.dev/devopsre/akeyless-public/akeyless-action:latest
        with:
          api-url: https://api.gateway.akeyless.celo-networks-dev.org
          access-id: p-kf9vjzruht6l
          static-secrets: '{"/static-secrets/devops-circle/alvaro-test-opstack-sepolia/gs-admin-private-key":"GS_ADMIN_PRIVATE_KEY"}'

      - name: Deploy L1 contracts
        run: |
          cd packages/contracts-bedrock
          forge script scripts/Deploy.s.sol:Deploy --private-key $GS_ADMIN_PRIVATE_KEY --rpc-url $L1_RPC_URL --slow
          # --broadcast
        env:
          L1_RPC_KIND: alchemy
          DEPLOYMENT_CONTEXT: getting-started
