name: Deploy Contracts
on:
  push:
    branches:
      - alvarof2/contracts
  workflow_dispatch:
    inputs:
      simulate:
        required: false
        type: boolean
        default: true

jobs:
  deploy-contracts:
    runs-on: ubuntu-latest
    permissions: # Must change the job token permissions to use Akeyless JWT auth
      id-token: write
      contents: read
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Akeyless get L1 URL
        uses: docker://us-west1-docker.pkg.dev/devopsre/akeyless-public/akeyless-action:latest
        with:
          api-url: https://api.gateway.akeyless.celo-networks-dev.org
          access-id: p-kf9vjzruht6l
          static-secrets: '{"/static-secrets/devops-circle/alvaro-test-opstack-sepolia/l1-rpc-url":"L1_RPC_URL"}'

      - name: Akeyless get GS ADMIN private key
        uses: docker://us-west1-docker.pkg.dev/devopsre/akeyless-public/akeyless-action:latest
        with:
          api-url: https://api.gateway.akeyless.celo-networks-dev.org
          access-id: p-kf9vjzruht6l
          static-secrets: '{"/static-secrets/devops-circle/alvaro-test-opstack-sepolia/gs-admin-private-key":"GS_ADMIN_PRIVATE_KEY"}'

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Deploy L1 contracts
        run: |
          export IMPL_SALT=$(openssl rand -hex 32)
          cd packages/contracts-bedrock
          ./scripts/getting-started/config.sh
          if [[ -z "${SIMULATE}" ]] || [[ $SIMULATE ]]
          then
            forge script scripts/Deploy.s.sol:Deploy --private-key $GS_ADMIN_PRIVATE_KEY --rpc-url $L1_RPC_URL --slow
          else
            echo "broadcast"
            # forge script scripts/Deploy.s.sol:Deploy --private-key $GS_ADMIN_PRIVATE_KEY --broadcast --rpc-url $L1_RPC_URL --slow
          fi
        env:
          SIMULATE: ${{ inputs.simulate }}
          L1_RPC_KIND: alchemy
          DEPLOYMENT_CONTEXT: test-alvaro
          GS_ADMIN_ADDRESS: '0x19c1696408E63d670ab8177bfafB0D37e9F3ed82'
          GS_BATCHER_ADDRESS: '0x0F82E82268FA5de5070A088e54eAbc2dec07D615'
          GS_PROPOSER_ADDRESS: '0x8D20f1E387cDF78c4AF42F61FB48B1Be72056FEb'
          GS_SEQUENCER_ADDRESS: '0xF20B236A87e26D1Ac7290D0F70f637af8145D54e'
