name: Docker Build Scan
on:
  workflow_dispatch:

jobs:
  build-container-op-stack-go:
    uses: ./.github/workflows/docker-generic-workflow.yaml
    with:
      registry: us-west1-docker.pkg.dev/devopsre/dev-images/optimism
      tags: op-stack-go-${{ github.sha }}
      dockerfile: ops/docker/op-stack-go/Dockerfile

  build-container-ci-builder:
    uses: ./.github/workflows/docker-generic-workflow.yaml
    if: false
    with:
      registry: us-west1-docker.pkg.dev/devopsre/dev-images/optimism
      tags: op-ci-builder-${{ github.sha }}
      dockerfile: ops/docker/ci-builder/Dockerfile

  build-container-op-node:
    uses: ./.github/workflows/docker-generic-workflow.yaml
    needs: build-container-op-stack-go
    with:
      registry: us-west1-docker.pkg.dev/devopsre/dev-images/optimism
      tags: op-node-${{ github.sha }}
      dockerfile: op-node/Dockerfile
      build-args: OP_STACK_GO_BUILDER=us-west1-docker.pkg.dev/devopsre/dev-images/optimism:op-stack-go-${{ github.sha }}

  build-container-op-batcher:
    uses: ./.github/workflows/docker-generic-workflow.yaml
    needs: build-container-op-stack-go
    with:
      registry: us-west1-docker.pkg.dev/devopsre/dev-images/optimism
      tags: op-batcher-${{ github.sha }}
      dockerfile: op-batcher/Dockerfile
      build-args: OP_STACK_GO_BUILDER=us-west1-docker.pkg.dev/devopsre/dev-images/optimism:op-ci-builder-${{ github.sha }}

  build-container-op-proposer:
    uses: ./.github/workflows/docker-generic-workflow.yaml
    needs: build-container-op-stack-go
    with:
      registry: us-west1-docker.pkg.dev/devopsre/dev-images/optimism
      tags: op-proposer-${{ github.sha }}
      dockerfile: op-proposer/Dockerfile
      build-args: OP_STACK_GO_BUILDER=us-west1-docker.pkg.dev/devopsre/dev-images/optimism:op-ci-builder-${{ github.sha }}

  build-container-op-challenger:
    uses: ./.github/workflows/docker-generic-workflow.yaml
    if: false
    with:
      registry: us-west1-docker.pkg.dev/devopsre/dev-images/optimism
      tags: op-challenger-${{ github.sha }}
      dockerfile: op-challenger/Dockerfile
      build-args: OP_STACK_GO_BUILDER=us-west1-docker.pkg.dev/devopsre/dev-images/optimism:op-ci-builder-${{ github.sha }}

  build-container-proxyd:
    uses: ./.github/workflows/docker-generic-workflow.yaml
    if: true
    with:
      registry: us-west1-docker.pkg.dev/devopsre/dev-images/optimism
      tags: op-proxyd-${{ github.sha }}
      dockerfile: proxyd/Dockerfile

  build-container-op-ufm:
    uses: ./.github/workflows/docker-generic-workflow.yaml
    if: false
    with:
      registry: us-west1-docker.pkg.dev/devopsre/dev-images/optimism
      tags: op-ufm-${{ github.sha }}
      dockerfile: op-ufm/Dockerfile

  build-container-ops-bedrock-l1:
    uses: ./.github/workflows/docker-generic-workflow.yaml
    if: false
    with:
      registry: us-west1-docker.pkg.dev/devopsre/dev-images/optimism
      tags: op-bedrock-l1-${{ github.sha }}
      dockerfile: ops-bedrock/Dockerfile.l1

  build-container-ops-bedrock-l2:
    uses: ./.github/workflows/docker-generic-workflow.yaml
    if: false
    with:
      registry: us-west1-docker.pkg.dev/devopsre/dev-images/optimism
      tags: op-bedrock-l2-${{ github.sha }}
      dockerfile: ops-bedrock/Dockerfile.l2

  build-container-ops-bedrock:
    uses: ./.github/workflows/docker-generic-workflow.yaml
    if: false
    with:
      registry: us-west1-docker.pkg.dev/devopsre/dev-images/optimism
      tags: ops-bedrock-${{ github.sha }}
      dockerfile: ops-bedrock/Dockerfile.stateviz

  build-container-indexer:
    uses: ./.github/workflows/docker-generic-workflow.yaml
    if: false
    with:
      registry: us-west1-docker.pkg.dev/devopsre/dev-images/optimism
      tags: op-indexer-${{ github.sha }}
      dockerfile: indexer/Dockerfile

  build-container-op-heartbeat:
    uses: ./.github/workflows/docker-generic-workflow.yaml
    needs: build-container-op-stack-go
    if: false
    with:
      registry: us-west1-docker.pkg.dev/devopsre/dev-images/optimism
      tags: op-heartbeat-${{ github.sha }}
      dockerfile: op-heartbeat/Dockerfile
      build-args: OP_STACK_GO_BUILDER=us-west1-docker.pkg.dev/devopsre/dev-images/optimism:op-ci-builder-${{ github.sha }}

  build-container-op-program:
    uses: ./.github/workflows/docker-generic-workflow.yaml
    needs: build-container-op-stack-go
    if: false
    with:
      registry: us-west1-docker.pkg.dev/devopsre/dev-images/optimism
      tags: op-program-${{ github.sha }}
      dockerfile: op-program/Dockerfile
      build-args: OP_STACK_GO_BUILDER=us-west1-docker.pkg.dev/devopsre/dev-images/optimism:op-ci-builder-${{ github.sha }}

  build-container-endpoint-monitor:
    uses: ./.github/workflows/docker-generic-workflow.yaml
    if: false
    with:
      registry: us-west1-docker.pkg.dev/devopsre/dev-images/optimism
      tags: op-endpoint-monitor-${{ github.sha }}
      dockerfile: endpoint-monitor/Dockerfile

  build-container-opwheel:
    uses: ./.github/workflows/docker-generic-workflow.yaml
    needs: build-container-op-stack-go
    if: false
    with:
      registry: us-west1-docker.pkg.dev/devopsre/dev-images/optimism
      tags: op-opwheel-${{ github.sha }}
      dockerfile: op-wheel/Dockerfile
      build-args: OP_STACK_GO_BUILDER=us-west1-docker.pkg.dev/devopsre/dev-images/optimism:op-ci-builder-${{ github.sha }}
